// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAISy88MUdF0al-PjCGWpqUcbQI0cumzYo',
    appId: '1:1097879132279:android:bf2ec0e3494d7a1ca58e72',
    messagingSenderId: '1097879132279',
    projectId: 'meraj3iapp',
    databaseURL: 'https://meraj3iapp-default-rtdb.firebaseio.com',
    storageBucket: 'meraj3iapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIHdqrmUN6HBQ1uBOq8_9VpvDh3sCBjE',
    appId: '1:1097879132279:ios:b2f9475bd1f66ac1a58e72',
    messagingSenderId: '1097879132279',
    projectId: 'meraj3iapp',
    databaseURL: 'https://meraj3iapp-default-rtdb.firebaseio.com',
    storageBucket: 'meraj3iapp.firebasestorage.app',
    androidClientId: '1097879132279-bd0ssd789t9ja3ok04l7ae1dcj57s1uj.apps.googleusercontent.com',
    iosClientId: '1097879132279-cu52tjseem9f9vsnr13isp9uabaig8t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIP7jV13xT6RmAuOePI7BPKI6M2S69UmU',
    appId: '1:1097879132279:web:733b383ab5e49610a58e72',
    messagingSenderId: '1097879132279',
    projectId: 'meraj3iapp',
    authDomain: 'meraj3iapp.firebaseapp.com',
    databaseURL: 'https://meraj3iapp-default-rtdb.firebaseio.com',
    storageBucket: 'meraj3iapp.firebasestorage.app',
    measurementId: 'G-PMZ45BT0HB',
  );
}
